In [1]:
import sklearn
from sklearn.datasets import load_iris 
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [2]:
import pandas as pd

iris = load_iris()

iris_data = iris.data # 피처 : 꽃받힘의 너비 길이 , 꽃잎의 너비 길이
iris_label = iris.target # 아이리스 품종 : 정답

print("iris target: " , iris_label)
print("iris target 명 : ", iris.target_names)

iris target:  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target 명 :  ['setosa' 'versicolor' 'virginica']

In [3]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

In [4]:
iris_df = pd . DataFrame(data=iris_data,columns=iris.feature_names)
iris_df["label"] = iris.target

iris_df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [5]:
# 학습셋과 테스트 셋으로 나누기

X_train, X_test, Y_train, Y_test = train_test_split(iris_data, iris_label, test_size=0.2,train_size=0.8, random_state=1)

In [6]:
dt_clf = DecisionTreeClassifier(random_state=1)

In [7]:
dt_clf.fit(X_train,Y_train)

DecisionTreeClassifier(random_state=1)

In [8]:
pred = dt_clf.predict(X_test)

In [9]:
pred

array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       2, 0, 2, 1, 0, 0, 1, 2])

In [10]:
from sklearn.metrics import accuracy_score
print("예측 정확도 : ", accuracy_score(Y_test, pred))

예측 정확도 :  0.9666666666666667

In [11]:
from sklearn.model_selection import KFold
import numpy as np

Kfold = KFold(n_splits = 5)
cv_accuracy = []

In [12]:
n_iter = 0
features = iris.data
label = iris.target
cv_accuracy = []

for train_index, text_index in Kfold.split(features):
    X_train, X_test = features[train_index],features[text_index]
    Y_train, Y_test = label[train_index],label[text_index]

    dt_clf.fit(X_train,Y_train)
    pred = dt_clf.predict(X_test)
    n_iter += 1

    accuracy = np.round(accuracy_score(Y_test,pred),4)

    train_size = X_train.shape[0]
    test_size =X_test.shape[0]
    print("교차검증 정홛도 : ",accuracy)
    print("학습 데이터 크기 : ",train_size)
    print("검증데이터크기 : ",test_size)
    cv_accuracy.append(accuracy)
    
print("평균 검증 정확도",np.mean(cv_accuracy))

교차검증 정홛도 :  1.0
학습 데이터 크기 :  120
검증데이터크기 :  30
교차검증 정홛도 :  1.0
학습 데이터 크기 :  120
검증데이터크기 :  30
교차검증 정홛도 :  0.9
학습 데이터 크기 :  120
검증데이터크기 :  30
교차검증 정홛도 :  0.9333
학습 데이터 크기 :  120
검증데이터크기 :  30
교차검증 정홛도 :  0.7333
학습 데이터 크기 :  120
검증데이터크기 :  30
평균 검증 정확도 0.91332

In [13]:
iris_df["label"].value_counts()

0    50
1    50
2    50
Name: label, dtype: int64

In [14]:
# stratifiedKFold -->

In [15]:
Kfold = KFold(n_splits = 3)
cv_accuracy = []

for train_index, text_index in Kfold.split(iris_df):
    n_iter +=1
    label_train = iris_df["label"].iloc[train_index]
    label_test = iris_df["label"].iloc[text_index]
    print("학습레이블 데이터 분포 : ", label_train.value_counts())
    print("검증레이블 데이터 분포 : ", label_test.value_counts())

학습레이블 데이터 분포 :  1    50
2    50
Name: label, dtype: int64
검증레이블 데이터 분포 :  0    50
Name: label, dtype: int64
학습레이블 데이터 분포 :  0    50
2    50
Name: label, dtype: int64
검증레이블 데이터 분포 :  1    50
Name: label, dtype: int64
학습레이블 데이터 분포 :  0    50
1    50
Name: label, dtype: int64
검증레이블 데이터 분포 :  2    50
Name: label, dtype: int64

In [16]:
from sklearn.model_selection import StratifiedGroupKFold

# skf = StratifiedFold(n_splits = 3)
# skf = StratifiedFold(n_splits = 3)
skf = StratifiedGroupKFold(n_splits = 3)

n_iter = 0

for train_index, test_index in skf.split(iris_df, iris_df["label"]):
    n_iter +=1
    label_train = iris_df["label"].iloc[train_index]
    label_test = iris_df["label"].iloc[test_index]
    print("학습레이블 데이터 분포 : ", label_train.value_counts())
    print("검증레이블 데이터 분포 : ", label_test.value_counts())

학습레이블 데이터 분포 :  1    50
2    50
0    49
Name: label, dtype: int64
검증레이블 데이터 분포 :  0    1
Name: label, dtype: int64
학습레이블 데이터 분포 :  0    50
1    50
2    50
Name: label, dtype: int64
검증레이블 데이터 분포 :  Series([], Name: label, dtype: int64)
학습레이블 데이터 분포 :  0    50
1    50
2    50
Name: label, dtype: int64
검증레이블 데이터 분포 :  Series([], Name: label, dtype: int64)

In [17]:
#####################

from sklearn.model_selection import StratifiedKFold

# 레이블 비율을 유지하는 3-Fold 교차 검증
skf = StratifiedKFold(
    n_splits=3,
    shuffle=True,
    random_state=1
)

n_iter = 0

for train_index, test_index in skf.split(
    iris_df.drop(columns=["label"]),
    iris_df["label"]
):
    n_iter += 1

    label_train = iris_df["label"].iloc[train_index]
    label_test = iris_df["label"].iloc[test_index]

    print(f"\n[{n_iter}번째 Fold]")
    print("학습 레이블 데이터 분포:")
    print(label_train.value_counts().sort_index())

    print("검증 레이블 데이터 분포:")
    print(label_test.value_counts().sort_index())

[1번째 Fold]
학습 레이블 데이터 분포:
0    33
1    33
2    34
Name: label, dtype: int64
검증 레이블 데이터 분포:
0    17
1    17
2    16
Name: label, dtype: int64

[2번째 Fold]
학습 레이블 데이터 분포:
0    33
1    34
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
0    17
1    16
2    17
Name: label, dtype: int64

[3번째 Fold]
학습 레이블 데이터 분포:
0    34
1    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
0    16
1    17
2    17
Name: label, dtype: int64

In [54]:
dt_clf = DecisionTreeClassifier(random_state=156)
skfold = StratifiedGroupKFold(n_splits = 3)
n_iter = 0
cv_accuracy = []

features = iris.data
label = iris.target



for train_index, test_index in skfold.split(features, label):
    X_train, X_test = features [train_index] , features[test_index]
    Y_train, Y_test = label[train_index], label[test_index]
    
    dt_clf.fit(X_train,Y_train)
    pred = dt_clf.predict(X_test)

    n_iter +=1
    accuracy = np.round(accuracy_score ( Y_test,pred),4)

    cv_accuracy.append(accuracy)

print("평균 검증 정확도 : ",np.round(np.mean(cv_accuracy),4))

# print(f"\n평균 교차 검증 정확도: {np.mean(cv_accuracy):.4f}")

ValueError: Found array with 0 sample(s) (shape=(0, 4)) while a minimum of 1 is required.

In [35]:

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
import numpy as np

n_iter = 0
cv_accuracy = []

features = iris.data
label = iris.target

dt_clf = DecisionTreeClassifier(random_state=1)

for train_index, test_index in skf.split(features, label):
    X_train, X_test = features[train_index], features[test_index]
    Y_train, Y_test = label[train_index], label[test_index]

    # 모델 학습
    dt_clf.fit(X_train, Y_train)

    # 검증 데이터 예측
    pred = dt_clf.predict(X_test)

    # 정확도 계산
    accuracy = accuracy_score(Y_test, pred)
    cv_accuracy.append(accuracy)

    n_iter += 1
    print(f"{n_iter}번째 Fold 정확도: {accuracy:.4f}")

print(f"\n평균 교차 검증 정확도: {np.mean(cv_accuracy):.4f}")

1번째 Fold 정확도: 0.9600
2번째 Fold 정확도: 0.9400
3번째 Fold 정확도: 0.9200

평균 교차 검증 정확도: 0.9400

In [36]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(dt_clf, features, label, scoring = "accuracy",cv = skf)

print("교차 검증별 정확도 : ", np.round(scores , 4))
print("평균 검증 정확도 : ", np.round(np.mean(scores) , 4))

교차 검증별 정확도 :  [0.96 0.94 0.92]
평균 검증 정확도 :  0.94

In [41]:

from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(
    iris.data,
    iris.target,
    test_size=0.2,
    random_state=121,
    stratify=iris.target
)

parameters = {
    "max_depth": [1, 2, 3],
    "min_samples_split": [2, 3]
}

In [46]:

from sklearn.model_selection import GridSearchCV

dtree = DecisionTreeClassifier(random_state=156)

grid_dtree = GridSearchCV(
    estimator=dtree,
    param_grid=parameters,
    cv=3,
    scoring="accuracy",
    refit=True
)

grid_dtree.fit(X_train, Y_train)

scores_df = pd.DataFrame(grid_dtree.cv_results_)

scores_df[
    [
        "params",
        "mean_test_score",
        "rank_test_score",
        "split0_test_score",
        "split1_test_score",
        "split2_test_score"
    ]
]

,params,mean_test_score,rank_test_score,split0_test_score,split1_test_score,split2_test_score
0,"{'max_depth': 1, 'min_samples_split': 2}",0.658333,5,0.650,0.675,0.65
1,"{'max_depth': 1, 'min_samples_split': 3}",0.658333,5,0.650,0.675,0.65
2,"{'max_depth': 2, 'min_samples_split': 2}",0.925000,3,0.975,0.950,0.85
3,"{'max_depth': 2, 'min_samples_split': 3}",0.925000,3,0.975,0.950,0.85
4,"{'max_depth': 3, 'min_samples_split': 2}",0.933333,1,1.000,0.950,0.85
5,"{'max_depth': 3, 'min_samples_split': 3}",0.933333,1,1.000,0.950,0.85

In [47]:

from sklearn.model_selection import GridSearchCV

dtree = DecisionTreeClassifier(random_state=156)

grid_dtree = GridSearchCV(
    estimator=dtree,
    param_grid=parameters,
    cv=3,
    scoring="accuracy",
    refit=True
)

grid_dtree.fit(X_train, Y_train)

scores_df = pd.DataFrame(grid_dtree.cv_results_)

scores_df[
    [
        "params",
        "mean_test_score",
        "rank_test_score",
        "split0_test_score",
        "split1_test_score",
        "split2_test_score"
    ]
]

,params,mean_test_score,rank_test_score,split0_test_score,split1_test_score,split2_test_score
0,"{'max_depth': 1, 'min_samples_split': 2}",0.658333,5,0.650,0.675,0.65
1,"{'max_depth': 1, 'min_samples_split': 3}",0.658333,5,0.650,0.675,0.65
2,"{'max_depth': 2, 'min_samples_split': 2}",0.925000,3,0.975,0.950,0.85
3,"{'max_depth': 2, 'min_samples_split': 3}",0.925000,3,0.975,0.950,0.85
4,"{'max_depth': 3, 'min_samples_split': 2}",0.933333,1,1.000,0.950,0.85
5,"{'max_depth': 3, 'min_samples_split': 3}",0.933333,1,1.000,0.950,0.85

In [48]:
grid_dtree.best_params_

{'max_depth': 3, 'min_samples_split': 2}

In [49]:
grid_dtree.best_score_

0.9333333333333332

In [50]:
estimator=grid_dtree.best_estimator_

pred = estimator.predict(X_test)
print(accuracy_score(Y_test, pred))

0.9666666666666667

In [ ]:
from sklearn.preprocessing import LabelEncoder

items = ["tv","냉장고","전자레인지", " 컴퓨터", " 선풍기" , "믹서","믹서","믹서"]

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print(labels)

In [ ]:
encoder.classes_

In [28]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ["tv","냉장고","전자레인지", "컴퓨터", "선풍기" , "선풍기","믹서","믹서"]

items = np.array(items).reshape(-1,1)
items

array([['tv'],
       ['냉장고'],
       ['전자레인지'],
       ['컴퓨터'],
       ['선풍기'],
       ['선풍기'],
       ['믹서'],
       ['믹서']], dtype='<U5')

In [29]:
oh_encoder = OneHotEncoder()
oh_encoder.fit(items)
oh_labels = oh_encoder.transform(items)

print(oh_labels.toarray())
print(oh_labels.shape)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
(8, 6)

In [30]:
df = pd.DataFrame({'items':["tv","냉장고","전자레인지", " 컴퓨터", "선풍기" , "선풍기","믹서","믹서"]})
df

   items
0     tv
1    냉장고
2  전자레인지
3    컴퓨터
4    선풍기
5    선풍기
6     믹서
7     믹서

In [31]:
pd.get_dummies(df)

   items_ 컴퓨터  items_tv  items_냉장고  items_믹서  items_선풍기  items_전자레인지
0           0         1          0         0          0            0
1           0         0          1         0          0            0
2           0         0          0         0          0            1
3           1         0          0         0          0            0
4           0         0          0         0          1            0
5           0         0          0         0          1            0
6           0         0          0         1          0            0
7           0         0          0         1          0            0

In [32]:
from sklearn.datasets import load_iris
iris = load_iris()

iris_data = iris.data
iris_df = pd.DataFrame(data = iris_data,columns=iris.feature_names)

print (iris_df.mean())
print(iris_df.var())

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64

In [34]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

iris_df_scaled = pd.DataFrame(data = iris_scaled, columns= iris.feature_names)
print(iris_df_scaled.mean())
print(iris_df_scaled.var())

sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64

In [53]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

print(iris_df_scaled.min())

print(iris_df_scaled.max())

sepal length (cm)   -1.870024
sepal width (cm)    -2.433947
petal length (cm)   -1.567576
petal width (cm)    -1.447076
dtype: float64
sepal length (cm)    2.492019
sepal width (cm)     3.090775
petal length (cm)    1.785832
petal width (cm)     1.712096
dtype: float64